### ISSUE TITLE
Citation and Disclaimer breaking individual citation and disclaimers

### ISSUE THREAD

**Issue by HjalteParner** [ices-tools-prod/ICES_DataPortal#10]
I just noticed that the data portal seem to overrule the individual data portals disclaimer which self shouldn’t happened or be allowed. Doing this you break the individual data portals disclaimer yourself.

Instead you could / should tell the downloader to read the individual disclaimers.

Hjalte 

From: accessions@ices.dk <accessions@ices.dk> 
Sent: 10 May 2021 17:59
To: Mehdi Abbasi <mehdi.abbasi@ices.dk>
Cc: Accessions <accessions@ices.dk>; Accessions <accessions@ices.dk>
Subject: ICES Data Portal - Download file 

The data you have requested to download is now available 
https://data.ices.dk/downloads?guid=3ffb4c6c-c856-4e2d-bb63-76f4b182a034

This link will be available for 7 days.
DATA CITATION 
Data sources should be acknowledged by a citation. Detailed information and examples of citations can be found in ICES Data Policy: https://ices.dk/data/guidelines-and-policy/Pages/ICES-data-policy.aspx. 

A minimum requirement citation would include the following: 
“ICES Data Portal, 2021.ICES, Copenhagen.” 

Extended citation: 
ICES Data Portal, Extraction 10 May 2021 of data from https://data.ices.dk. ICES, Copenhagen 

Please acknowledge the following data sources when using the data:
Acoustic trawl surveys: Biotic data in acoustic trawl surveys. 2021. ICES 2021
Acoustic trawl surveys: Acoustic data in acoustic trawl surveys. 2021. ICES 2021
Fish trawl surveys: Biotic data in fish trawl surveys. 2021. ICES 2021

For any questions or comments, please contact accessions@ices.dk
Kind regards,
ICES Data Centre

International Council for the Exploration of the Sea
Email: accessions@ices.dk
Web: https://www.ices.dk

Tel: +45 3338 6718 Fax: +45 3393 4215
H.C.Andersens Boulevard 44 - 46
1553 Copenhagen V.Denmark

Read the latest ICES Data Centre e - News https://www.ices.dk/data/Pages/default.aspx 
________________________________________
This email has been generated by ICES Data Portal

**Comment by mehdiabbasi** [comment]
Individual disclaimer for dataportal from each MS

**Comment by HjalteParner** [comment]
?

**Comment by mehdiabbasi** [comment]
@HjalteParner The decision is to remove the Disclaimer from Data portal, but each dataset needs to include this extended citation for data portal when download WebAPI is called from Data portal:

Extended citation:
ICES Data Portal, Extraction 10 May 2021 of data from https://data.ices.dk. ICES, Copenhagen

Please acknowledge the following data sources when using the data:
Acoustic trawl surveys: Biotic data in acoustic trawl surveys. 2021. ICES 2021
Acoustic trawl surveys: Acoustic data in acoustic trawl surveys. 2021. ICES 2021

**Comment by HjalteParner** [comment]
@mehdiabbasi I've updated the disclaimer in ocean.

**Comment by mehdiabbasi** [comment]
@cmspinto The decision is to remove the Disclaimer from Data portal, but each dataset needs to include this extended citation for data portal when download WebAPI is called from Data portal:

Extended citation:
ICES Data Portal, Extraction 10 May 2021 of data from https://data.ices.dk. ICES, Copenhagen

Please acknowledge the following data sources when using the data:
Acoustic trawl surveys: Biotic data in acoustic trawl surveys. 2021. ICES 2021
Acoustic trawl surveys: Acoustic data in acoustic trawl surveys. 2021. ICES 2021

**Comment by mehdiabbasi** [comment]
@neil-ices-dk Can I keep DATA CITATION in DataPortal download email and just remove extended citation?                                                         

DATA CITATION
Data sources should be acknowledged by a citation. Detailed information and examples of citations can be found in ICES Data Policy: https://ices.dk/data/guidelines-and-policy/Pages/ICES-data-policy.aspx.

A minimum requirement citation would include the following:
“ICES Data Portal, 2021.ICES, Copenhagen.”

**Comment by neil-ices-dk** [comment]
> 
> 
> @neil-ices-dk Can I keep DATA CITATION in DataPortal download email and just remove extended citation?
> 
> DATA CITATION
> Data sources should be acknowledged by a citation. Detailed information and examples of citations can be found in ICES Data Policy: https://ices.dk/data/guidelines-and-policy/Pages/ICES-data-policy.aspx.
> 
> A minimum requirement citation would include the following:
> “ICES Data Portal, 2021.ICES, Copenhagen.”

does this mean that information on specific datasets/portals would not be included - would this information be in the disclaimer itself or up to the user to figure out the citation?

**Comment by mehdiabbasi** [comment]
@neil-ices-dk Extended citation specific datasets/portals is moved to each individual disclaimer as we agreed not to overrule the individual data portals disclaimer but I think DATA CITATION part is general and we can keep it in the email?

**Comment by neil-ices-dk** [comment]
that will work @mehdiabbasi as long as that is clear in the generic email where they can find info, we are covered 😺

**Comment by mehdiabbasi** [comment]
remove citation info from email and just refer to the individual disclaimer and also remove general disclaimer

**Comment by mehdiabbasi** [comment]
@HjalteParner Could you please implement extended citation for DataPortal for Acoustic download WebAPI 

Extended citation:
ICES Data Portal, Extraction 10 May 2021 of data from https://data.ices.dk. ICES, Copenhagen

Please acknowledge the following data sources when using the data:
Acoustic trawl surveys: Biotic data in acoustic trawl surveys. 2021. ICES 2021
Acoustic trawl surveys: Acoustic data in acoustic trawl surveys. 2021. ICES 2021
