### ISSUE TITLE
Alternative map icon to re-do the data search?

### ISSUE THREAD

**Issue by SebastianValanko** [ices-tools-prod/ICES_DataPortal#11]
The current icons could be improved, as the magnifying glass can be mistaken for zooming in and out
![image](https://user-images.githubusercontent.com/30894859/117804831-8ac58a00-b258-11eb-8253-9e7bd272938d.png)

something like this could help?
![image](https://user-images.githubusercontent.com/30894859/117804997-be081900-b258-11eb-988d-01d5c18470ae.png)

Or like this?
![image](https://user-images.githubusercontent.com/30894859/117805056-d11ae900-b258-11eb-8e21-37f01faa3107.png)

![image](https://user-images.githubusercontent.com/30894859/117805124-e4c64f80-b258-11eb-9a05-285484c57f41.png)

![image](https://user-images.githubusercontent.com/30894859/117805221-01fb1e00-b259-11eb-952c-5f570ce8f868.png)

**Comment by mehdiabbasi** [comment]
it is improved by adding the title to the icon for more clarification. Thanks @SebastianValanko
