### ISSUE TITLE
Topics: checkboxes are not intuitive

### ISSUE THREAD

**Issue by Osanna123** [ices-tools-prod/ICES_DataPortal#14]
Checkboxes in the Topics are not self-explanatory, and the big icons are the first ones to be pressed.
Maybe we could play with sizes? Add text?

**Comment by MalinWerner** [comment]
Test that says "Choose" in a larger tick box? 
Or help/instruction text that says "to choose a dataset klick the tick box".
I was wondering in general if an instruction/help-text could be present at different operations? You klick on "help/instructons" and can read more about what to do there, if you need it. Is that possible? To have a Help-bubble, that changes text depending on where you are but stays in position? Then the page stays rather clean, but you can easily fins mote instructions if you need it.

**Comment by mehdiabbasi** [comment]
help notification is implemented to guide user
