### ISSUE TITLE
Search edit: not intuitive

### ISSUE THREAD

**Issue by Osanna123** [ices-tools-prod/ICES_DataPortal#15]
It is hard for the first-time users to identify how to get back to their layer selection.
Maybe having a word 'Edit' would help?

**Comment by mehdiabbasi** [comment]
Add/Edit layer(s) to the map

**Comment by mehdiabbasi** [comment]
comment from Malin -> I am not a minimalistic person :) and would appreciate a text or two on what to do, eg.
"ICES data portal. Here you can find and download data by first adding layers to the map"
