### ISSUE TITLE
Conditions for data criteria

### ISSUE THREAD

**Issue by Osanna123** [ices-tools-prod/ICES_DataPortal#20]
Users expect to have conditions as 'or' for the same reference list, and 'and' for the different lists

**Comment by mehdiabbasi** [comment]
From Ingeborg: I've been working on the expectations for Data Criteria behaviour. I'd asked Malin to have a look at it but she got stuck in the document and we didn't have time to talk about it. My starting point was 'what do people in general expect when they select multiple data'. The 'AND' and 'OR' are technical 'AND' and 'OR', so from a programmer's perspective. Where 'AND-OR', both options should be allowed, when only one option is mentioned, this is basically the only option. Could you check if you get more or less my point: [https://community.ices.dk/Committees/DIG/DIG%202021/02.%20Background%20documents/user_expectation_dataportal_20210521.xlsx](https://community.ices.dk/Committees/DIG/DIG%202021/02.%20Background%20documents/user_expectation_dataportal_20210521.xlsx)

**Comment by mehdiabbasi** [comment]
For the same data criteria, all the time OR conditions will be applied and for different data criteria user can define AND-OR
