### ISSUE TITLE
download of file after selecting single species

### ISSUE THREAD

**Issue by Ingeborg1312** [ices-tools-prod/ICES_DataPortal#22]
I like the appearance of the portal. I played around and will report findings on a case by case basis.

What I did:
Dataset Themes: Fish trawl surveys
Advanced search:
Time period: 2018-2021
Data Criteria:
Survey=Sole Net Survey and
Species=Cancer pagurus
Download data

Expectation 1: I see the locations where Cancer pagurus has been caught in the survey in those years
Preference 1: I see (more or less) how many specimens of the species were caught, including the locations where it wasn't caught.
Expectation 2: the download contains the (a) haul information for all hauls (irrespective if the species has been caught or not), (b) the catch information for the selected species.

Expectation 1 is met, Preference 1 not.
Expectation 2 is partly met, for HH. But for HL I receive the catch information for all species in the selected years in the survey. One of the added values of this portal would be that I can easily select data for a single (or a subset) of species over multiple surveys/data sources.

**Comment by mehdiabbasi** [comment]
@vaishav Hi Vaishav, we had a short chat about the requirement of partial download ex. filtering based on Species. Could you please comment on this?

**Comment by mehdiabbasi** [comment]
Hi @HjalteParner, this is also relevant to Acoustic because Acoustic download is just available in the Cruise level and including full submission. If a user, filter some species or some of the logs in Acoustic data, Is it possible to download just that specific part of the data?

**Comment by HjalteParner** [comment]
@mehdiabbasi acoustic and biotic data from acoustic surveys cannot be compared to DATRAS data as they should be seen in context and the biotic data cannot be used quantitative - only qualitative. However I will bring it up in the acoustic governance group for discussion - next meeting in September.

**Comment by mehdiabbasi** [comment]
@HjalteParner yes, that is the issue to discuss with the acoustic governance group. What about combining different cruises in one file? One of the comments from DIG was the multiple files when users downloading Acoustic data.

**Comment by HjalteParner** [comment]
@mehdiabbasi I will discuss it with the acoustic governance group. However until then only downloads by cruise should be allowed.

**Comment by HjalteParner** [comment]
I've create an issue on this at https://github.com/ices-eg/wg_WGACOUSTICGOV/issues/21

**Comment by HjalteParner** [comment]
@mehdiabbasi as you can read from the comments at https://github.com/ices-eg/wg_WGACOUSTICGOV/issues/21 data from acoustic surveys need to be downloaded by cruise as currently is the case.
